---
title: "Using Databases"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE
)
```

## Setup

We start by loading our packages and creating a simple fitted workflow using `mtcars`.

```{r setup}
library(orbital)
library(recipes)
library(parsnip)
library(workflows)
```

```{r}
rec_spec <- recipe(mpg ~ disp, data = mtcars) |>
  step_impute_mean(all_numeric_predictors()) |>
  step_normalize(all_numeric_predictors())

lm_spec <- linear_reg()

wf_spec <- workflow(rec_spec, lm_spec)
wf_fit <- fit(wf_spec, data = mtcars)
```

then create our orbital object.

```{r}
orbital_obj <- orbital(wf_fit)
orbital_obj
```

## SQL

```{r}
library(DBI)
library(RSQLite)

con_sqlite <- dbConnect(SQLite(), path = ":memory:")
mtcars_sqlite <- copy_to(con_sqlite, mtcars, name = "mtcars_table")

predict(orbital_obj, mtcars_sqlite)
```

```{r}
predict(orbital_obj, mtcars_sqlite) |>
  collect()
```

## Spark

```{r}
library(sparklyr)

con_spark <- spark_connect(master = "local")
mtcars_spark <- copy_to(con_spark, mtcars, overwrite = TRUE)

predict(orbital_obj, mtcars_spark)
```

```{r}
predict(orbital_obj, mtcars_spark) |>
  collect()
```

## duckdb

```{r}
library(duckdb)

con_duckdb <- dbConnect(duckdb(dbdir = ":memory:"))
mtcars_duckdb <- dplyr::copy_to(con_duckdb, mtcars)

predict(orbital_obj, mtcars_duckdb)
```

```{r}
predict(orbital_obj, mtcars_duckdb) |>
  collect()
```

## arrow

```{r}
library(arrow)
mtcars_arrow <- as_arrow_table(mtcars)

predict(orbital_obj, mtcars_arrow)
```

```{r}
predict(orbital_obj, mtcars_arrow) |>
  collect()
```
